
# inflation size
inflation: 1
# lookahead distance for updating grid map
lookahead: 6

# Topics that RRT listens to
# TODO: change this to the pose topic published particle filter
pose_topic: "pf/pose/odom"
scan_topic: "scan"


# Topics that RRT publishes to
# TODO: add your own
# visualization

# Parameters for RRT
step: 0.3 # used for expanding the tree
goal_threshold: 0.15 # close enough to goal
iteration: 200 # main loop iteration nums