
# inflation size
inflation: 1
# lookahead distance for updating grid map
lookahead: 5

# Topics that RRT listens to
# TODO: change this to the pose topic published particle filter
pose_topic: "pf/pose/odom"
scan_topic: "scan"


# Topics that RRT publishes to
# TODO: add your own
# visualization

# Parameters for RRT
step: 0.3
goal_threshold: 0.15