# inflation size
inflation: 3
# lookahead distance for finding a waypoint
lookahead_dist: 1.0
sample_depth: 3.0
sample_width: 1.5
neighbor_dist: 1.0

# Pure Pursuit
# angle coefficient
angle_factor: 0.1
nominal_speed: 1.0
angle_speed: 1.0

# Topics that RRT listens to
# TODO: change this to the pose topic published particle filter
pose_topic: "pf/pose/odom"
scan_topic: "scan"


# Topics that RRT publishes to
# TODO: add your own
# visualization

# Parameters for RRT
step: 0.4 # used for expanding the tree
goal_threshold: 0.2 # close enough to goal
iteration: 50 # main loop iteration nums