# MapMetaData Initialize
#frame_id: "map"
#height: 400
#width: 200
#resolution: 0.05
#map_publisher: "map"

# inflation size
inflation: 1
# lookahead distance for updating grid map
lookahead: 5




# Topics that RRT listens to
# TODO: add your own
# TODO: change this to the pose topic published particle filter
pose_topic: "pf/pose/odom"
scan_topic: "scan"


# Topics that RRT publishes to
# TODO: add your own
# visualization

# TODO: add Parameters for RRT